# Generated by Django 5.0.6 on 2025-11-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='rasi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='familymember',
            name='rasi',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
