# Generated by Django 5.0.6 on 2025-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donorprofile_rasi_familymember_rasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='tamil_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
