# Generated by Django 5.0.6 on 2025-10-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
