# Generated by Django 5.0.6 on 2025-10-22 05:07

from django.db import migrations, models


def assign_donor_numbers(apps, schema_editor):
    DonorProfile = apps.get_model('accounts', 'DonorProfile')
    db_alias = schema_editor.connection.alias
    existing_max = (
        DonorProfile.objects.using(db_alias)
        .aggregate(max_number=models.Max('donor_number'))
        .get('max_number')
    ) or 0
    next_number = existing_max
    for profile in DonorProfile.objects.using(db_alias).order_by('id'):
        if profile.donor_number:
            continue
        next_number += 1
        DonorProfile.objects.using(db_alias).filter(pk=profile.pk).update(donor_number=next_number)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_familymember_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='donor_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(assign_donor_numbers, migrations.RunPython.noop),
    ]
