# Generated by Django 5.0.6 on 2025-12-13 10:54

from django.db import migrations, models


GOTHRAS = [
    "ஆத்ரேயா",
    "நைத்திருவ காட்ச்யபம்",
    "காஷ்யப கோத்திரம்",
    "வாதூல கோத்திரம்",
    "கார்கேயா",
    "கவுண்டின்யா",
    "கெளஷிகா",
    "கெளதமர்",
    "பரத்வாஜா",
    "ஹரிதா",
    "செளநகா",
    "சாண்டில்யர்",
    "ஸ்ரீவத்ஸ கோத்திரம்",
    "விஷ்ணு கோத்திரம்",
    "லத்ஸ் கோத்திரம்",
]


def create_default_gothra_options(apps, schema_editor):
    GothraOption = apps.get_model("accounts", "GothraOption")
    for position, name in enumerate(GOTHRAS, start=1):
        GothraOption.objects.create(name=name, display_order=position)


def delete_default_gothra_options(apps, schema_editor):
    GothraOption = apps.get_model("accounts", "GothraOption")
    GothraOption.objects.filter(name__in=GOTHRAS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_donorprofile_custom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GothraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.RunPython(
            create_default_gothra_options,
            delete_default_gothra_options,
        ),
    ]
