# Generated by Django 5.0.6 on 2026-01-19 11:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donorprofile_monthly_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance for the current month/year', max_digits=12),
        ),
    ]
