# Generated by Django 5.0.6 on 2026-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_donorprofile_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_phone_number', models.CharField(max_length=15)),
                ('feedback', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donor_feedback',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
