# Generated by Django 5.0.6 on 2026-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_donorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='pooja_registration_access',
            field=models.BooleanField(default=False, help_text='Controls whether donor can add/save pooja registrations.'),
        ),
    ]
