# Generated by Django 5.0.6 on 2026-04-02

from django.db import migrations, models


NAKSHATRAS = [
    "அசுவினி",
    "பரணி",
    "கிருத்திகை",
    "ரோகிணி",
    "மிருகசீரிடம்",
    "திருவாதிரை",
    "புனர்பூசம்",
    "பூசம்",
    "ஆயில்யம்",
    "மகம்",
    "பூரம்",
    "உத்தரம்",
    "அஸ்தம்",
    "சித்திரை",
    "சுவாதி",
    "விசாகம்",
    "அனுஷம்",
    "கேட்டை",
    "மூலம்",
    "பூராடம்",
    "உத்திராடம்",
    "திருவோணம்",
    "அவிட்டம்",
    "சதயம்",
    "பூரட்டாதி",
    "உத்திரட்டாதி",
    "ரேவதி",
]

RASIS = [
    "மேஷம்",
    "ரிஷபம்",
    "மிதுனம்",
    "கடகம்",
    "சிம்மம்",
    "கன்னி",
    "துலாம்",
    "விருச்சிகம்",
    "தனுசு",
    "மகரம்",
    "கும்பம்",
    "மீனம்",
]


def create_default_nakshatra_and_rasi_options(apps, schema_editor):
    NakshatraOption = apps.get_model("accounts", "NakshatraOption")
    RasiOption = apps.get_model("accounts", "RasiOption")
    for position, name in enumerate(NAKSHATRAS, start=1):
        NakshatraOption.objects.create(name=name, display_order=position)
    for position, name in enumerate(RASIS, start=1):
        RasiOption.objects.create(name=name, display_order=position)


def delete_default_nakshatra_and_rasi_options(apps, schema_editor):
    NakshatraOption = apps.get_model("accounts", "NakshatraOption")
    RasiOption = apps.get_model("accounts", "RasiOption")
    NakshatraOption.objects.filter(name__in=NAKSHATRAS).delete()
    RasiOption.objects.filter(name__in=RASIS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_donorprofile_payment_delete_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="NakshatraOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="RasiOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.RunPython(
            create_default_nakshatra_and_rasi_options,
            delete_default_nakshatra_and_rasi_options,
        ),
    ]
