# Generated by Django 5.0.6 on 2025-11-10 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('header_text', models.TextField()),
                ('footer_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedPooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='featured-poojas/')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PoojaDayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('weekday', 'Weekday'), ('code', 'Template Code'), ('tamil_star', 'Tamil Star')], default='code', max_length=32)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DonorMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('summary_text', models.TextField()),
                ('tamil_text', models.TextField(blank=True)),
                ('gothra_details', models.CharField(blank=True, max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_texts', to=settings.AUTH_USER_MODEL)),
                ('day_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pooja.poojadayoption')),
            ],
            options={
                'ordering': ('donor', 'preferred_date'),
            },
        ),
        migrations.CreateModel(
            name='PoojaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_group_header', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pooja.poojaoption')),
            ],
            options={
                'ordering': ('parent_id', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PoojaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_group_registration', models.BooleanField(default=False)),
                ('post_prasadam', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Pooja Confirmed'), ('completed', 'Pooja Completed')], default='pending', max_length=16)),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pooja.poojadayoption')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooja_registrations', to=settings.AUTH_USER_MODEL)),
                ('pooja_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='pooja.poojaoption')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PoojaRegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('tamil_star', models.CharField(blank=True, max_length=128)),
                ('gothra', models.CharField(blank=True, max_length=128)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pooja.poojaregistration')),
            ],
            options={
                'ordering': ('registration', 'name'),
            },
        ),
    ]
