# Generated by Django 5.0.6 on 2025-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='featured-poojas/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
