# Generated by Django 5.0.6 on 2025-09-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0002_featuredpooja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredpooja',
            options={'ordering': ('-created_at', 'id')},
        ),
        migrations.RemoveField(
            model_name='featuredpooja',
            name='order',
        ),
        migrations.AddField(
            model_name='featuredpooja',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
