# Generated by Django 5.0.6 on 2025-09-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0003_alter_featuredpooja_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayArchana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='archana/main/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OneDayArchanaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='archana/items/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('archana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pooja.onedayarchana')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
