# Generated by Django 5.0.6 on 2025-11-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0003_poojacartsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPoojaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_kind', models.CharField(choices=[('recurring', 'Recurring'), ('one_time_extra', 'One-time extra')], default='recurring', max_length=32)),
                ('recurrence_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_occurrence', models.DateField(blank=True, null=True)),
                ('last_occurrence', models.DateField(blank=True, null=True)),
                ('one_time_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pause_until', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cart_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pooja.poojadayoption')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_plans', to=settings.AUTH_USER_MODEL)),
                ('origin_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_recurring_plans', to='pooja.poojaregistration')),
                ('pooja_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_plans', to='pooja.poojaoption')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='recurringpoojaplan',
            constraint=models.UniqueConstraint(
                condition=models.Q(recurrence_kind='recurring'),
                fields=('donor', 'pooja_option', 'day_option', 'recurrence_kind'),
                name='pooja_recurring_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='recurringpoojaplan',
            constraint=models.UniqueConstraint(
                condition=models.Q(recurrence_kind='one_time_extra'),
                fields=('donor', 'pooja_option', 'day_option', 'recurrence_kind', 'one_time_date'),
                name='pooja_one_time_unique',
            ),
        ),
    ]
