# Generated by Django 5.0.6 on 2025-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0004_recurringpoojaplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpoojaplan',
            name='recurrence_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=32),
        ),
    ]
