# Generated by Codex on 2025-09-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0004_onedayarchana_onedayarchanaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaoption',
            name='is_group_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poojaoption',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pooja.poojaoption'),
        ),
        migrations.AlterModelOptions(
            name='poojaoption',
            options={'ordering': ('parent_id', 'code')},
        ),
    ]
