# Generated by Django 5.0.6 on 2025-10-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0004_poojaregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Pooja Confirmed'), ('completed', 'Pooja Completed')], default='pending', max_length=16),
        ),
    ]
