# Generated by Django 5.0.6 on 2025-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0005_alter_recurringpoojaplan_recurrence_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpoojaplan',
            name='pause_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
