# Generated by Django 5.0.6 on 2025-10-22 05:07

from django.db import migrations, models


def assign_registration_numbers(apps, schema_editor):
    Registration = apps.get_model('pooja', 'PoojaRegistration')
    db_alias = schema_editor.connection.alias
    existing_max = (
        Registration.objects.using(db_alias)
        .aggregate(max_number=models.Max('registration_number'))
        .get('max_number')
    ) or 0
    next_number = existing_max
    for registration in Registration.objects.using(db_alias).order_by('id'):
        if registration.registration_number:
            continue
        next_number += 1
        Registration.objects.using(db_alias).filter(pk=registration.pk).update(registration_number=next_number)


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0005_poojaregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaregistration',
            name='registration_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(assign_registration_numbers, migrations.RunPython.noop),
    ]
