# Generated by Django 5.0.6 on 2025-10-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0006_seed_pooja_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedayarchanaitem',
            name='archana',
        ),
        migrations.DeleteModel(
            name='OneDayArchana',
        ),
        migrations.DeleteModel(
            name='OneDayArchanaItem',
        ),
    ]
