# Generated by Django 5.0.6 on 2025-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0007_remove_onedayarchanaitem_archana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poojaoption',
            options={'ordering': ('parent_id', 'sort_order', 'code')},
        ),
        migrations.AddField(
            model_name='poojaoption',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
