# Generated by Django 5.0.6 on 2025-10-04 07:07

from django.db import migrations, models


def set_initial_display_order(apps, schema_editor):
    PoojaDayOption = apps.get_model('pooja', 'PoojaDayOption')
    for position, option in enumerate(PoojaDayOption.objects.order_by('code', 'id'), start=1):
        option.display_order = position
        option.save(update_fields=['display_order'])


def noop_reverse(apps, schema_editor):
    """No-op reverse migration."""
    # Keeping a no-op so rollback leaves the default zero values in place.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0008_alter_poojaoption_options_poojaoption_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojadayoption',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_initial_display_order, noop_reverse),
        migrations.AlterModelOptions(
            name='poojadayoption',
            options={'ordering': ('display_order', 'id')},
        ),
    ]
