# Generated by Django 5.0.6 on 2026-01-02 10:13

from django.db import migrations, models

SPECIAL_ANNOUNCEMENTS = [
    ("ADMSG1", "* சங்கடசதுர்த்தி - ஆத்தங்கரை பிள்ளையார் அபிஷேகம்"),
    ("ADMSG2", "*காலபைரவர் அர்சனை"),
    ("ADMSG3", "*ப்ரதோஷ பூஜை"),
    ("ADMSG4", "* ஆஞ்சனேயர் அர்ச்சனை, பானகம் ப்ரசாதம்"),
    ("ADMSG5", "*ஆஞ்சனேயர் அர்ச்சனை, கற்கட்டு ப்ரசாதம்"),
    (
        "ADMSG6",
        "*ராகு காலத்தில் ராகு பகவானுக்கு அபிஷேகம், நீல புதிய வஸ்திரம், நீல நிரம் பூ அர்சனை, கருப்பு உளுந்து சுன்டல் நெய்வேத்தியம்",
    ),
]


def create_special_announcements(apps, schema_editor):
    SpecialAnnouncement = apps.get_model("pooja", "SpecialAnnouncement")
    for label, description in SPECIAL_ANNOUNCEMENTS:
        SpecialAnnouncement.objects.update_or_create(
            label=label,
            defaults={"description": description},
        )


def remove_special_announcements(apps, schema_editor):
    SpecialAnnouncement = apps.get_model("pooja", "SpecialAnnouncement")
    labels = [label for label, _ in SPECIAL_ANNOUNCEMENTS]
    SpecialAnnouncement.objects.filter(label__in=labels).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0009_enforce_registration_member_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Announcement',
                'verbose_name_plural': 'Special Announcements',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RunPython(create_special_announcements, remove_special_announcements),
    ]
