# Generated by Django 5.0.6 on 2025-10-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0009_alter_poojadayoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poojaoption',
            options={'ordering': ('parent_id', 'code')},
        ),
        migrations.RemoveField(
            model_name='poojaoption',
            name='sort_order',
        ),
    ]
