# Generated by Django 5.0.6 on 2026-01-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0013_seed_daily_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaCartSnapshotExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_snapshot_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PoojaCartSnapshotExportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.PositiveIntegerField(null=True)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_phone', models.CharField(blank=True, max_length=32)),
                ('items', models.JSONField(blank=True, default=list)),
                ('source_updated_at', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pooja.poojacartsnapshotexportbatch')),
            ],
            options={
                'ordering': ('donor_id', 'id'),
            },
        ),
    ]
