# Generated by Django 5.0.6 on 2026-02-27 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0023_exclude_special_poojas_from_ubhayam_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poojaregistration',
            index=models.Index(fields=['status', 'start_date'], name='pooja_reg_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='poojaregistration',
            index=models.Index(fields=['status', 'created_at'], name='pooja_reg_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpoojaplan',
            index=models.Index(fields=['is_active', 'recurrence_kind', 'start_date'], name='pooja_plan_active_start_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpoojaplan',
            index=models.Index(fields=['is_active', 'recurrence_kind', 'next_occurrence'], name='pooja_plan_active_next_idx'),
        ),
    ]
