# Generated by Django 5.0.6 on 2026-05-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0026_exclude_all_special_poojas_from_ubhayam_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbhayamDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('tamil_stars', models.JSONField(blank=True, default=list)),
                ('pooja_day_option_ids', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubhayam_date_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
    ]
