# Generated by Django 5.0.6 on 2026-05-28 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0027_ubhayamdateoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbhayamAllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubhayam_allocation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UbhayamAllocationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_of_month', models.CharField(max_length=16)),
                ('tamil_star', models.TextField(blank=True)),
                ('pooja_day_option', models.TextField(blank=True)),
                ('donor_id', models.TextField(blank=True)),
                ('donor_name', models.TextField(blank=True)),
                ('donor_mobile_number', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pooja.ubhayamallocationrun')),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='ubhayamallocationrun',
            constraint=models.UniqueConstraint(fields=('month', 'run_number'), name='ubhayam_allocation_run_unique_month_number'),
        ),
        migrations.AddConstraint(
            model_name='ubhayamallocationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('month',), name='ubhayam_allocation_run_unique_latest_per_month'),
        ),
        migrations.AddConstraint(
            model_name='ubhayamallocationrow',
            constraint=models.UniqueConstraint(fields=('run', 'date'), name='ubhayam_allocation_row_unique_run_date'),
        ),
    ]
