# Generated by Django 5.0.6 on 2025-11-10 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pooja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('mode', models.CharField(choices=[('neft', 'NEFT'), ('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Credit/Debit'), ('auto_debit', 'Auto Debit'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('payment_month', models.DateField(blank=True, help_text='Represents the month the payment covers', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pooja.poojaregistration')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
