# Generated by Django 5.0.6 on 2026-01-08 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_expenserecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinePaymentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combine_payment_mappings', to=settings.AUTH_USER_MODEL)),
                ('parent_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combine_payment_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='combinepaymentmapping',
            constraint=models.UniqueConstraint(fields=('main_donor', 'parent_donor'), name='unique_main_parent_mapping'),
        ),
    ]
