# Generated by Django 5.0.6 on 2026-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_combinepaymentmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinepaymentmapping',
            name='main_donor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='combinepaymentmapping',
            name='main_donor_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='combinepaymentmapping',
            name='parent_donor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='combinepaymentmapping',
            name='parent_donor_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
