# Generated by Django 5.0.6 on 2026-01-12 11:54

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_combinepaymentmapping_effective_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinepaymentmapping',
            name='effective_from',
            field=models.DateField(default=payments.models._default_effective_from, help_text='First month (inclusive) when this combine mapping is active.'),
        ),
    ]
