# Generated by Django 5.0.6 on 2026-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_restructure_donation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passbookentry',
            new_name='payments_pa_donor_i_87ed55_idx',
            old_name='payments_pas_donor_i_idx',
        ),
        migrations.RenameIndex(
            model_name='passbookentry',
            new_name='payments_pa_donor_i_7ff352_idx',
            old_name='payments_pas_donor_i2_idx',
        ),
    ]
