# Generated by Django 5.0.6 on 2026-03-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_payments_pas_donor_i_idx_payments_pa_donor_i_87ed55_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
