# Generated by Django 5.0.6 on 2026-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_expenserecord_comments_expenserecord_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('group_key', models.CharField(choices=[('poojari', 'We pay to poojari for'), ('coordinator', 'We pay to co ordinator'), ('bank', 'We remit to bank'), ('other', 'Other')], default='other', max_length=24)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('group_key', 'display_order', 'name', 'id'),
            },
        ),
    ]
