# Generated by Django 5.0.6 on 2026-03-09 06:46

from django.db import migrations


DEFAULT_EXPENSE_CATEGORIES = [
    ("For Til oil", "poojari"),
    ("For Neivedhyam", "poojari"),
    ("For Navagraha pooja", "poojari"),
    ("For Pradosham", "poojari"),
    ("For spl pooja", "poojari"),
    ("Archana & Abishekam", "poojari"),
    ("Post expenses", "coordinator"),
    ("Salary for 2 ladies", "coordinator"),
    ("Repair & maintenance work in temple", "coordinator"),
    ("For FD", "bank"),
]


def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("payments", "ExpenseCategory")
    ExpenseRecord = apps.get_model("payments", "ExpenseRecord")

    next_order_by_group = {}
    for index, (name, group_key) in enumerate(DEFAULT_EXPENSE_CATEGORIES, start=1):
        ExpenseCategory.objects.get_or_create(
            name=name,
            defaults={
                "group_key": group_key,
                "display_order": index,
                "is_active": True,
            },
        )
        next_order_by_group[group_key] = max(next_order_by_group.get(group_key, 0), index)

    known_names = {
        name.strip().lower()
        for name in ExpenseCategory.objects.values_list("name", flat=True)
        if isinstance(name, str) and name.strip()
    }

    extra_categories = (
        ExpenseRecord.objects.exclude(category__isnull=True)
        .exclude(category__exact="")
        .values_list("category", flat=True)
        .distinct()
    )
    for category_name in extra_categories:
        if not isinstance(category_name, str):
            continue
        trimmed = category_name.strip()
        if not trimmed:
            continue
        normalized = trimmed.lower()
        if normalized in known_names:
            continue
        next_order = next_order_by_group.get("other", 0) + 1
        ExpenseCategory.objects.create(
            name=trimmed,
            group_key="other",
            display_order=next_order,
            is_active=True,
        )
        next_order_by_group["other"] = next_order
        known_names.add(normalized)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_expensecategory"),
    ]

    operations = [
        migrations.RunPython(seed_expense_categories, noop_reverse),
    ]
