# Generated by Django 5.0.6 on 2026-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_accountcatalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcatalogue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='accountcatalogue',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
