# Generated by Django 5.0.6 on 2026-03-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_incomecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCatalogue',
        ),
    ]
