# Generated by Django 5.0.6 on 2026-03-31 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_accountcatalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionIncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('category', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_no', models.CharField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addition_income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_date', '-created_at'),
            },
        ),
    ]
