# Generated by Django 5.0.6 on 2026-06-10 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_additionincomerecord'),
        ('pooja', '0028_ubhayamallocationrun_ubhayamallocationrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_month__isnull', False), ('registration__isnull', True), ('status', 'pending')), fields=('donor', 'payment_month'), name='uniq_pending_monthly_due_per_donor_month'),
        ),
    ]
